In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [76]:
# 1~8호선 심도 데이터
depth_1to8_df = pd.read_csv("../../data/raw/서울교통공사_1~8호선_역사심도정보_20250814.csv", encoding='cp949')
depth_1to8_df

,연번,호선,역명,층수,형식,지반고,레일면고,선로기준정거장깊이,정거장깊이,비고
0,1,1,서울,B2,섬식,129.99,117.04,12.95,11.85,"4호선,경의중앙선,공항철도환승"
1,2,1,시청,B2,상대식,129.97,118.82,11.15,10.05,2호선환승
2,3,1,종각,B2,상대식,128.77,116.24,12.53,11.43,NaN
3,4,1,종로3가,B2,상대식,124.38,112.04,12.34,11.24,"3,5호선환승"
4,5,1,종로5가,B2,상대식,121.75,109.26,12.49,11.39,NaN
...,...,...,...,...,...,...,...,...,...,...
271,272,8,단대오거리,B3,상대식,153.71,139.5,14.21,13.11,NaN
272,273,8,신흥,B2,상대식,143.89,128.47,15.42,14.32,NaN
273,274,8,수진,B2,상대식,137.63,122.76,14.87,13.77,NaN
274,275,8,모란,B3,상대식,128.39,106.23,22.16,21.06,분당선환승
275,276,8,암사역사공원,B2,상대식,-,-,18.38,17.28,NaN

In [77]:
# 1~8호선 필요 컬럼 추출 후 컬럼명 변환
depth_1to8_cleaned_df = depth_1to8_df[['역명', '층수', '정거장깊이']].copy()
depth_1to8_cleaned_df.rename(columns={'역명' : '지하철역', '정거장깊이' : '심도'}, inplace=True)
depth_1to8_cleaned_df

       지하철역  층수     심도
0        서울  B2  11.85
1        시청  B2  10.05
2        종각  B2  11.43
3      종로3가  B2  11.24
4      종로5가  B2  11.39
..      ...  ..    ...
271   단대오거리  B3  13.11
272      신흥  B2  14.32
273      수진  B2  13.77
274      모란  B3  21.06
275  암사역사공원  B2  17.28

[276 rows x 3 columns]

In [78]:
# 9호선 심도 데이터
depth_9_df = pd.read_csv("../../data/raw/서울교통공사_9호선 2_3단계 역사 심도 정보_20250813.csv", encoding='cp949')
depth_9_df

,연번,호선,정거장명,정거장층수,형식,지반고,레일면고,선로기준 정거장 깊이(m),승강장기준 정거장 깊이(m),비고
0,1,9,언주,B5,상대식,136.48,100.510,35.970,34.870,NaN
1,2,9,선정릉,B4,상대식,141.10,114.580,26.520,25.420,분당선환승
2,3,9,삼성중앙,B2,상대식,129.40,107.496,21.904,20.804,NaN
3,4,9,봉은사,B2,상대식,117.54,96.520,21.020,19.920,NaN
4,5,9,종합운동장,B4,상대식,114.57,81.265,33.305,32.205,2호선환승
5,6,9,삼전,B2,상대식,114.33,93.889,20.441,19.341,NaN
6,7,9,석촌고분,B4,섬식,114.26,95.680,18.580,17.480,NaN
7,8,9,석촌,B2,섬식,114.75,90.910,23.840,22.740,8호선환승
8,9,9,송파나루,B2,섬식,114.65,96.169,18.481,17.381,NaN
9,10,9,한성백제,B2,섬식,115.06,95.990,19.070,17.970,NaN
10,11,9,올림픽공원,B3,섬식,120.38,96.910,23.470,22.370,5호선환승
11,12,9,둔촌오륜,B2,섬식,127.48,104.970,22.510,21.410,NaN
12,13,9,중앙보훈병원,B2,복합식,139.00,124.380,14.620,13.520,NaN

In [79]:
# 9호선 필요 컬럼 추출 후 컬럼명 변환
depth_9_cleaned_df = depth_9_df[['정거장명', '정거장층수', '승강장기준 정거장 깊이(m)']].copy()
depth_9_cleaned_df.rename(columns={'정거장명':'지하철역', '정거장층수':'층수', '승강장기준 정거장 깊이(m)':'심도'}, inplace=True)
depth_9_cleaned_df

      지하철역  층수      심도
0       언주  B5  34.870
1      선정릉  B4  25.420
2     삼성중앙  B2  20.804
3      봉은사  B2  19.920
4    종합운동장  B4  32.205
5       삼전  B2  19.341
6     석촌고분  B4  17.480
7       석촌  B2  22.740
8     송파나루  B2  17.381
9     한성백제  B2  17.970
10   올림픽공원  B3  22.370
11    둔촌오륜  B2  21.410
12  중앙보훈병원  B2  13.520

In [80]:
# 1~8호선 필요 컬럼 추출 데이터와 9호선 필요 컬럼 추출 데이터를 행 방향으로 병합
depth_all_df = pd.concat([depth_1to8_cleaned_df, depth_9_cleaned_df], axis=0, ignore_index=True)
depth_all_df

       지하철역  층수      심도
0        서울  B2  11.850
1        시청  B2  10.050
2        종각  B2  11.430
3      종로3가  B2  11.240
4      종로5가  B2  11.390
..      ...  ..     ...
284    송파나루  B2  17.381
285    한성백제  B2  17.970
286   올림픽공원  B3  22.370
287    둔촌오륜  B2  21.410
288  중앙보훈병원  B2  13.520

[289 rows x 3 columns]

In [81]:
depth_all_df['지하철역'].unique()

array(['서울', '시청', '종각', '종로3가', '종로5가', '동대문', '동묘앞', '신설동', '제기동',
       '청량리', '을지로입구', '을지3가', '을지4가', '동대문역사문화공원', '신당', '상왕십리', '왕십리',
       '한양대', '뚝섬', '성수', '건대입구', '구의', '강변', '잠실나루', '잠실', '잠실새내',
       '종합운동장', '삼성 ', '선릉', '역삼', '강남', '교대', '서초', '방배', '사당', '낙성대',
       '서울대입구', '봉천', '신림', '신대방', '구로디지털', '대림', '신도림', '문래', '영등포구청',
       '당산', '합정', '홍대입구', '신촌', '이대', '아현', '충정로', '용두', '신답', '용답',
       '도림천', '양천구청', '신정네거리', '지축', '구파발', '연신내', '불광', '녹번', '홍제',
       '무악재', '독립문', '경복궁', '안국', '을지로3가', '충무로', '동대입구', '약수', '금호',
       '옥수', '압구정', '신사', '잠원', '고속터미널', '남부터미널', '양재', '매봉', '도곡', '대치',
       '학여울', '대청', '일원', '수서', '가락시장', '경찰병원', '오금', '당고개', '상계', '노원',
       '창동', '쌍문', '수유', '미아', '미아삼거리', '길음', '성신여대입구', '한성대입구', '혜화',
       '명동', '회현', '서울역', '숙대입구', '삼각지', '신용산', '이촌', '동작', '총신대입구',
       '남태령', '방화', '개화산', '김포공항', '송정', '마곡', '발산', '우장산', '화곡', '까치산',
       '신정', '목동', '오목교', '양평', '영등포시장', '신길', '여의도', '여의나루', '마포', '공덕',
       '애오게', '서대문', '광화문', '을지로4가', '동대문운동장', '청구', '신금호', '행당', '마장',
       '답십리', '장한평', '군자', '아차산', '광나루', '천호', '강동', '길동', '굽은다리', '명일',
       '고덕', '상일동', '둔촌', '올림픽공원', '방이', '개롱', '거여', '마천', '강일', '미사',
       '하남풍산', '하남시청', '하남검단산', '응암', '역촌', '독바위', '구산', '새절', '증산',
       'DMC', '월드컵경기장', '마포구청', '망원', '상수', '광흥창', '대흥', '효창공원앞', '녹사평',
       '이태원', '한강진', '버티고개', '창신', '보문', '안암', '고려대', '월곡', '상월곡', '돌곶이',
       '석계', '태릉입구', '화랑대', '봉화산', '신내', '장암', '도봉산', '수락산', '마들', '중계',
       '하계', '공릉', '먹골', '중화', '상봉', '면목', '사가정', '용마산', '중곡', '어린이대공원',
       '뚝섬유원지', '청담', '강남구청', '학동', '논현', '반포', '내방', '이수', '남성', '숭실대',
       '상도', '장승배기', '보라매', '신풍', '남구로', '가산디지털단지', '철산', '광명', '천왕',
       '온수', '암사', '강동구청', '몽촌토성', '석촌', '송파', '문정', '장지', '복정', '남위례',
       '산성', '남한산성입구', '단대오거리', '신흥', '수진', '모란', '암사역사공원', '언주', '선정릉',
       '삼성중앙', '봉은사', '삼전', '석촌고분', '송파나루', '한성백제', '둔촌오륜', '중앙보훈병원'],
      dtype=object)

In [82]:
non_seoul = [
    # 5호선 (하남)
    '미사', '하남검단산', '하남시청(덕풍?신장)', '하남풍산',
    # 7호선 (경기/인천)
    '광명사거리', '굴포천', '까치울', '부천시청', '부평구청',
    '삼산체육관', '상동', '신중동', '춘의', '철산',
    # 8호선 (성남)
    '남위례', '남한산성입구(성남법원.검찰청)', '단대오거리',
    '모란', '복정', '산성', '수진', '신흥',
]

depth_all_cleaned_df = depth_all_df[~depth_all_df['지하철역'].isin(non_seoul)].copy()
depth_all_cleaned_df

       지하철역  층수      심도
0        서울  B2  11.850
1        시청  B2  10.050
2        종각  B2  11.430
3      종로3가  B2  11.240
4      종로5가  B2  11.390
..      ...  ..     ...
284    송파나루  B2  17.381
285    한성백제  B2  17.970
286   올림픽공원  B3  22.370
287    둔촌오륜  B2  21.410
288  중앙보훈병원  B2  13.520

[278 rows x 3 columns]

In [83]:
depth_all_cleaned_df['지하철역'].unique()

array(['서울', '시청', '종각', '종로3가', '종로5가', '동대문', '동묘앞', '신설동', '제기동',
       '청량리', '을지로입구', '을지3가', '을지4가', '동대문역사문화공원', '신당', '상왕십리', '왕십리',
       '한양대', '뚝섬', '성수', '건대입구', '구의', '강변', '잠실나루', '잠실', '잠실새내',
       '종합운동장', '삼성 ', '선릉', '역삼', '강남', '교대', '서초', '방배', '사당', '낙성대',
       '서울대입구', '봉천', '신림', '신대방', '구로디지털', '대림', '신도림', '문래', '영등포구청',
       '당산', '합정', '홍대입구', '신촌', '이대', '아현', '충정로', '용두', '신답', '용답',
       '도림천', '양천구청', '신정네거리', '지축', '구파발', '연신내', '불광', '녹번', '홍제',
       '무악재', '독립문', '경복궁', '안국', '을지로3가', '충무로', '동대입구', '약수', '금호',
       '옥수', '압구정', '신사', '잠원', '고속터미널', '남부터미널', '양재', '매봉', '도곡', '대치',
       '학여울', '대청', '일원', '수서', '가락시장', '경찰병원', '오금', '당고개', '상계', '노원',
       '창동', '쌍문', '수유', '미아', '미아삼거리', '길음', '성신여대입구', '한성대입구', '혜화',
       '명동', '회현', '서울역', '숙대입구', '삼각지', '신용산', '이촌', '동작', '총신대입구',
       '남태령', '방화', '개화산', '김포공항', '송정', '마곡', '발산', '우장산', '화곡', '까치산',
       '신정', '목동', '오목교', '양평', '영등포시장', '신길', '여의도', '여의나루', '마포', '공덕',
       '애오게', '서대문', '광화문', '을지로4가', '동대문운동장', '청구', '신금호', '행당', '마장',
       '답십리', '장한평', '군자', '아차산', '광나루', '천호', '강동', '길동', '굽은다리', '명일',
       '고덕', '상일동', '둔촌', '올림픽공원', '방이', '개롱', '거여', '마천', '강일', '하남시청',
       '응암', '역촌', '독바위', '구산', '새절', '증산', 'DMC', '월드컵경기장', '마포구청', '망원',
       '상수', '광흥창', '대흥', '효창공원앞', '녹사평', '이태원', '한강진', '버티고개', '창신',
       '보문', '안암', '고려대', '월곡', '상월곡', '돌곶이', '석계', '태릉입구', '화랑대', '봉화산',
       '신내', '장암', '도봉산', '수락산', '마들', '중계', '하계', '공릉', '먹골', '중화', '상봉',
       '면목', '사가정', '용마산', '중곡', '어린이대공원', '뚝섬유원지', '청담', '강남구청', '학동',
       '논현', '반포', '내방', '이수', '남성', '숭실대', '상도', '장승배기', '보라매', '신풍',
       '남구로', '가산디지털단지', '광명', '천왕', '온수', '암사', '강동구청', '몽촌토성', '석촌',
       '송파', '문정', '장지', '남한산성입구', '암사역사공원', '언주', '선정릉', '삼성중앙', '봉은사',
       '삼전', '석촌고분', '송파나루', '한성백제', '둔촌오륜', '중앙보훈병원'], dtype=object)

In [84]:
depth_all_cleaned_df['지하철역'] = depth_all_cleaned_df['지하철역'].str.replace('역$', '', regex=True)
depth_all_cleaned_df

       지하철역  층수      심도
0        서울  B2  11.850
1        시청  B2  10.050
2        종각  B2  11.430
3      종로3가  B2  11.240
4      종로5가  B2  11.390
..      ...  ..     ...
284    송파나루  B2  17.381
285    한성백제  B2  17.970
286   올림픽공원  B3  22.370
287    둔촌오륜  B2  21.410
288  중앙보훈병원  B2  13.520

[278 rows x 3 columns]

In [85]:
depth_final_df = depth_all_cleaned_df.groupby('지하철역').agg({
    '층수' : 'max',
    '심도' : 'max'
}).reset_index()

depth_final_df

        지하철역  층수     심도
0        DMC  B2  11.57
1       가락시장  B4  23.33
2    가산디지털단지  B4  26.67
3         강남  B2  11.96
4       강남구청  B3  21.72
..       ...  ..    ...
237       홍제  B3  15.82
238       화곡  B3  18.90
239      화랑대  B2  15.57
240       회현  B4  22.09
241    효창공원앞  B3  19.33

[242 rows x 3 columns]